slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: mapping

    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    odom_topic: /odometry/filtered

    transform_publish_period: 0.02
    map_update_interval: 3.0
    minimum_time_interval: 0.1

    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    throttle_scans: 2

    resolution: 0.02
    min_laser_range: 0.01
    max_laser_range: 6.0
    occupancy_threshold: 0.55

    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 10.0
    scan_queue_size: 200

    use_scan_matching: true
    use_scan_barycenter: false
    link_scan_maximum_distance: 0.8
    link_match_minimum_response_fine: 0.4

    do_loop_closing: false
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.55

    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.08

    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    distance_variance_penalty: 1.0
    angle_variance_penalty: 1.4
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.25
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    min_pass_through: 2
    debug_logging: false
    enable_interactive_mode: true
    ceres_num_threads: 12