slam_toolbox:
  ros__parameters:
    use_sim_time: True
    mode: mapping

    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    odom_topic: /odometry/filtered

    transform_publish_period: 0.04
    transform_timeout: 0.5
    tf_buffer_duration: 60.0

    map_update_interval: 2.0
    minimum_time_interval: 0.2

    throttle_scans: 2         
    scan_queue_size: 100       
    scan_buffer_size: 30       
    scan_buffer_maximum_scan_distance: 8.0

    resolution: 0.02          
    min_laser_range: 0.15     
    max_laser_range: 8.0
    occupancy_threshold: 0.55
 
    minimum_travel_distance: 0.10  
    minimum_travel_heading: 0.10    

    use_scan_matching: true
    use_scan_barycenter: false

    link_scan_maximum_distance: 1.0
    link_match_minimum_response_fine: 0.45

    do_loop_closing: false

    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.55

    correlation_search_space_dimension: 0.2
    correlation_search_space_resolution: 0.02
    correlation_search_space_smear_deviation: 0.05

    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    distance_variance_penalty: 1.2
    angle_variance_penalty: 1.6

    minimum_angle_penalty: 1.0
    minimum_distance_penalty: 0.6

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.25
    coarse_angle_resolution: 0.0349

    use_response_expansion: true

    min_pass_through: 2
    debug_logging: false
    enable_interactive_mode: true
    ceres_num_threads: 5
