ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.1 
    two_d_mode: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true

    odom0: /odom
    odom0_config: [false, false, false, # xyz pose
                   false, false, false, # rpy pose
                   true,  true,  false, # xyz vel
                   false, false, true,  # rpy vel
                   false, false, false]
    odom0_differential: false
    odom0_relative: true 

    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, true,  
                  false, false, false,
                  false, false, true,
                  true,  false, false] 
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true